-- Supabase/Postgres schema for the public accountability ledger.
create table if not exists analysts (
  id bigint generated by default as identity primary key,
  name text not null,
  outlet text not null,
  verification_level text not null default 'unverified',
  long_term_roi numeric,
  sample_size integer,
  notes text,
  created_at timestamptz default now()
);

create table if not exists picks (
  id bigint generated by default as identity primary key,
  week integer not null,
  game text not null,
  player text not null,
  market text not null,
  side text not null,
  line numeric,
  odds integer,
  sportsbook text,
  grade text,
  estimated_probability numeric,
  implied_probability numeric,
  edge numeric,
  bet_to text,
  pass_at text,
  rationale text,
  status text not null default 'WATCH',
  kickoff_at timestamptz,
  locked_at timestamptz,
  result text,
  units numeric default 0,
  source_url text,
  created_at timestamptz default now()
);

create table if not exists pick_sources (
  pick_id bigint references picks(id) on delete cascade,
  analyst_id bigint references analysts(id) on delete cascade,
  stance text,
  source_line text,
  primary key(pick_id, analyst_id)
);

create table if not exists price_snapshots (
  id bigint generated by default as identity primary key,
  pick_id bigint references picks(id) on delete cascade,
  sportsbook text not null,
  line numeric,
  odds integer,
  captured_at timestamptz default now()
);

create index if not exists picks_week_idx on picks(week);
create index if not exists picks_status_idx on picks(status);
create index if not exists snapshots_pick_idx on price_snapshots(pick_id);
